### ISSUE TITLE
Incorrect parsing ('>' child element selector)

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [gymadarasz/xparser#2]
``` php
<?php
include 'vendor/autoload.php';
use gymadarasz\xparser\XNode;
$x = new XNode(
'<html>
    <head>
        <title>Test page</title>
    </head>
    <body>
                <div id="hello1" class="message">
                    <div>
                      <span>
                        ho
                      </span>
                    </div>
                </div>
    </body>
</html>');

        $before = $x->find('#hello1 > span')->inner();

// show document
echo $before;
```

return 

```
ho
```

But there are no node that satisfy this selector "#hello1 > span". The expected output should be "Not found" or something like this.

**Comment by gymadarasz** [comment]
It because the child selector '>' not implemented this library. I'll keep open this issue and if I find a quick solution, I'll implement it. 
Note: My goal is not to make a better CSS selection than e.g symphony. I want to make a realy fast html reader and/or manipulator lib for php, the css selection is just an 'extra' in this lib.
thanks

**Comment by gymadarasz** [comment]
I added the symfony css-selector lib for these cases when the XNode get an unexpected css selector, then use it otherwise find the elements as original algorithm.
