### ISSUE TITLE
incorrect parsing (inner classes)

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [gymadarasz/xparser#4]
``` php
<?php
include 'vendor/autoload.php';
use gymadarasz\xparser\XNode;
$x = new XNode(
'<html>
    <head>
        <title>Test page</title>
    </head>
    <body>
                <div class="hello2">
                  <span>1</span>
                </div>
                  <div class="hello2">
                    <div class="hello2">
                      2
                    </div>
                </div>
    </body>
</html>');

echo count($x->find('.hello2')->getElements());
```

outputs

`1`

but there are clearly 3 node satisfying the constraint

**Comment by gymadarasz** [comment]
Thank you for this issue and let me notice that this is the point when I got why is so quick this lib. Technically when you make a query which try to find something recursion in html struct the regex search time exponentially improve but If you try to find an exact element it seem to be very fast. So this lib fast incase if you know which is the element (or a few of elements) what you looking for and these elements aren't too deep in DOM tree in recursion.
When you can not know how many element will in your query incase I created a "getCount" function which relatively fast and give you how much element are in your selection, but it's not resolve the problem, It will be fix soon as possible..

**Comment by gymadarasz** [comment]
recursion detect added, see readme

**Comment by GuillaumeLeclerc** [comment]
And this is why we never do parsing with regex but with better techniques such as
- Recursive descent parsing
- CYK

**Comment by gymadarasz** [comment]
No, not never. Correctly, We never do parsing with regex when we don't know how big chance for a recursion.
It's depends what do we want e.g. think about the differents a getElementById() and the getElementsByTag() functions because if you know that there is no recursive struct in your document in the selection and only one element is in the document per "id" attribute so recursion impossible.
btw I measured it on a typically html page document, find the title all links and img tags replace these elements with this parser and others. the results are stable and very quick but slow if I want to find the e.g all div elements without marked any class or id attributes and these elements are in more than 8 deep recursion but the last scenario not too frequent...
The problem with the regex parsing is not that it impossible or slow. The problem is then if you don't sure that you will have not recursion. Othewise very quick.
