### ISSUE TITLE
Incorrect parsing (error not thrown)

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [gymadarasz/xparser#5]
``` php
<?php
include 'vendor/autoload.php';
use gymadarasz\xparser\XNode;
$x = new XNode(
'<html>
    <head>
        <title>Test page</title>
    </head>
    <body>
                <div class="hello2">
    </body>
</html>');

print_r($x->find('.hello2')->outer());
```

outputs

```
Array
(
)
```

I think an error should be thrown when tags are not closed.

Another way of doing this would be to "auto-close" tags. If you do this then I should not get an empty array here.

**Comment by gymadarasz** [comment]
Yes, I understand the problem but it is a validation and not a parser issue. The parser obviously return with an empty array because in your html source doesn't contains any valid `<div>` elements so I created a validation function for this issue. The validation is not too quick process and you don't have to use it every single html loading and parsing but if you aren't sure that your html is valid, you can check it before use:

``` php
if($x->validate()) {
  // ..do something here
  $x->find('.hello2')->outer();
}
else {
  // your html contains an invalid closure structure
  die('Invalid document!');
}
```
